### ISSUE TITLE
The site fidelity does not work well

### ISSUE THREAD

**Issue by lukey11-zz** [BCLab-UNM/CPFA-ARGoS#5]
Hi all,

The robot does not go back to the previous location when it uses site fidelity. It will go other location which is not very close to the site fidelity. The other issue is that, the site fidelity is not added into the site fidelity list. If you want to visualize the site fidelity, you will not see it.

**Comment by gmfricke** [comment]
The destination error had noise turned on by default. Noise is turned off by default now.
